site_name: Nota Legal

extra_css:
  - css/extra_css.css

theme:
  name: 'material'
  logo: 'img/icons/favicon.png'

nav:
  - Home: README.md
  - Análise de requisitos:
    - Guia de Estilo: Guia_de_Estilo.md
    - Análise Hierárquica de Tarefas: Analise_de_tarefas.md
  - Design, Avaliação e Desenvolvimento:
    - Avaliação Heurística: avaliacao_heuristica.md
  - Perfil do Usuário: 
    - Entrevista: entrevista.md
    - Personas: personas.md
    - Questionario: Questionario.md
  - Avaliação:
    - Planejamento: planejamentoAvaliacao.md