site_name: Nota Legal

extra_css:
  - css/extra_css.css

theme:
  name: 'material'
  logo: 'img/icons/favicon.png'

nav:
  - Home: README.md
  - Análise de requisitos:
    - Guia de Estilo: Guia_de_Estilo.md
    - Análise Hierárquica de Tarefas: Analise_de_tarefas.md
    - Storyboard: Storyboard.md 
    - Característica da Plataforma: caracteristicaDaPlataforma.md
  - Design, Avaliação e Desenvolvimento:
    - Avaliação Heurística: avaliacao_heuristica.md
  - Perfil do Usuário: 
    - Entrevista: entrevista.md
    - Personas: personas.md
    - Questionario: Questionario.md
  - Avaliação:
    - Planejamento protótipo de papel: planejamentoAvaliacao.md
    - Avaliação protótipo de papel: avaliacaoPrototipoPapel.md
    - Inspeção-Acessibilidade Web: inspecao.md
    - Planejamento protótipo de alta fidelidade: Planejamento_protipo_alta_fidelidade.md
    - Avaliação protótipo de alta fidelidade: avaliacaoPrototipoAltaFidelidade.md
    - Planejamento ASES: planejamentoASES.md
    - Avaliação ASES: avaliacaoAses.md
